# To build caddy docker image
FROM caddy:2.7-alpine

# Copy your custom Caddyfile
COPY deploy/Caddyfile /etc/caddy/Caddyfile

# Create directories for Caddy data and config
RUN mkdir -p /var/www/scripts /var/www/styles

# Static files for the website
COPY index.html /var/www/index.html
COPY scripts /var/www/scripts
COPY styles /var/www/styles
