services:
  server1:
    image: server
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    ports:
      - "8080:8081"
    depends_on:
      - redis-stack
    networks:
      - app_network

  server2:
    image: server
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    ports:
      - "8080:8082"
    depends_on:
      - redis-stack
      - db
    networks:
      - app_network

  server3:
    image: server
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    ports:
      - "8080:8083"
    depends_on:
      - redis-stack
    networks:
      - app_network

  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - app_network


  db:
    image: postgres:16-alpine  # Alpine is smaller and efficient
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=url_shortener_db
    ports:
      - "5432:5432"
    networks:
      - app_network

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # Optional: for HTTP/3 support
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./index.html:/var/www/index.html
      - ./scripts:/var/www/scripts
      - ./styles:/var/www/styles
    depends_on:
      - server1
      - server2
      - server3
    networks:
      - app_network

networks:
  app_network:
volumes:
  caddy_data:
  caddy_config: