# To build caddy docker image
FROM caddy:2.7-alpine

# Copy your custom Caddyfile
COPY Caddyfile /etc/caddy/Caddyfile

# Create directories for Caddy data and config
RUN mkdir -p /data /config

# Static files for the website
COPY index.html /var/www/index.html
COPY scripts /var/www/scripts
COPY styles /var/www/styles
