# Accept connections from any IP (Required for Docker)
bind 0.0.0.0

# Set a strong password
requirepass password

# Port to listen on
port 6379

# Enable Append Only File (AOF) for better data persistence
appendonly yes
appendfsync everysec

save 900 1      # RDB: Save if 1 key changes in 15 mins

aof-use-rdb-preamble yes # Use fast-loading hybrid format

# Set memory limits to prevent the container from crashing your host
maxmemory 256mb
maxmemory-policy allkeys-lru

# Log to standard output so 'docker logs' works correctly
logfile ""
